[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared= {path = "../shared"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ctrlc = "3.5.0"
egui = "0.33.0"
eframe = "0.33.0"
